### ISSUE TITLE
'govendor' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by rumes** [sezzle/generator-gin-api#2]
I have installed yoman and generator-gin-api and when i create project using "yo gin-api" it gives

> 'govendor' is not recognized as an internal or external command,
operable program or batch file.
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn govendor ENOENT
    at notFoundError (C:\Users\rumesh\AppData\Roaming\npm\node_modules\generator-gin-api\node_modules\yeoman-generator\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\rumesh\AppData\Roaming\npm\node_modules\generator-gin-api\node_modules\yeoman-generator\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\rumesh\AppData\Roaming\npm\node_modules\generator-gin-api\node_modules\yeoman-generator\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
'make' is not recognized as an internal or external command,
operable program or batch file.

what is wrong

**Comment by killianbrackey** [comment]
@rumes It looks like you need to install govendor.  Try running: ```go get -u github.com/kardianos/govendor```
